import React, {useEffect} from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import { v4 as uuidv4 } from 'uuid';
import Home from './Home';
import AddPlayer from './AddPlayer';
import Game from './Game';
import {addQuestions, deleteSessionData} from './firebaseService';
import './App.css';
export const questions = [
    {
        category: "categories",
        questions: [
            "Autos",
            "Make Up",
            "Alkoholmarken",
            "Alkoholische Getränke",
            "Weinsorten",
            "Tiere",
            "Reime",
            "Namen",
            "Essen",
            "Länder",
            "Mordwaffen",
            "Clubs / bar",
            "Farben",
            "Orte",
            "Eis",
            "Serien",
            "Filme",
            "Nomen",
            "Webseiten",
            "Animes",
            "Mangas",
            "Podcasts",
            "Musicals",
            "Berühmte Zitate",
            "Märchen",
            "Süßwaren",
            "Kartenspiele",
            "Verkehrszeichen",
            "Videokonsolen",
            "Handy Marken",
            "Obstsorten",
            "Berühmte Gebäude",
            "Autoteile",
            "Kosmetikmarken",
            "Schmuckarten",
            "Tanzstile",
            "Musikinstrumente",
            // lustige und gewagte Kategorien:
            "Peinliche Momente",
            "Ungewöhnliche Hobbys",
            "Schuldige Vergnügungen",
            "Schlechte Gewohnheiten",
            "Kitschige Lieder",
            "Peinliche Fernsehsendungen",
            "Schlechte Filmtitel",
            "Unangemessene Witze",
            "Berühmte Modesünden",
            "Merkwürdige Phobien",
            "Seltsame Diäten",
            "Verrückte Gesetze",
            "Nahrungsmittel, die man nie essen würde",
            "Peinliche Erinnerungen",
            "Seltsame Internet-Trends",
            "Bizarre Erfindungen",
            "Absurde Wissenschaftstheorien",
            "Komische Haustiere",
            "Peinliche Teenie-Bands",
            "Verbotene Bücher",
            "Schlechte Tätowierungen",
            "Ungewöhnliche Ängste",
            "Schlechte Pick-Up-Lines",
            "Schlechte Frisuren",
            "Verrückte Partyerlebnisse",
            "Peinliche Geschichten aus der Kindheit",
            "Seltsame Mode-Trends",
            "Ungewöhnliche Sammelleidenschaften",
            "Seltsame Rituale",
            "Verrückte Traumerlebnisse",
            "Komische Gewohnheiten beim Schlafen",
            "Bekannte Filmfehler",
            "Merkwürdige Wettbewerbe",
            "Unmögliche Quizfragen",
            "Komische Essgewohnheiten",
            "Verrückte Berühmtheiten",
            "Unpassende Liedtexte",
            "Skurrile Berufe",
            "Bizarre Bräuche aus aller Welt",
            "Seltsame Traditionen",
            "Komische Festivals",
            "Mario Charaktere",
            "Eissorten",
            "Sexspielzeuge",
            "Schauspieler beginnend mit Buchstabe (rechter Nachbar sagt stopp)",
            "Automarken",
            "Sänger/Bands beginnend mit Buchstabe (rechter Nachbar sagt stopp)",
            "Sexpositionen",
            "Pornodarsteller/Innen",
            "Anmachsprüche",
            "Kosenamen",
            "Softdrinks",
            "Cocktails"
        ]
    },
    {
        category: "never_ever",
        questions: [
            "Ich hab noch nie gepupst",
            "Ich hab noch nie ins Pool gepinkelt",
            "Ich hab noch nie Alkohol getrunken",
            "Ich hab noch nie geweint",
            "Ich hatte noch nie Sex",
            "Ich habe noch nie dasselbe Geschlecht geküsst",
            "Ich habe noch nie das andere Geschlecht geküsst",
            "Ich hab noch nie mehr als 1 Person in 24 Stunden geküsst",
            "Ich hab noch nie von Alkohol gekotzt",
            "Ich hab noch nie in die Abwasch von jemanden gekotzt",
            "Ich bin noch nie im angetrunkenen Zustand mit dem Auto gefahren",
            "Ich hab noch nie meine Uhr bei einem festl verloren",
            "Ich hab noch nie wegen Alkohol geweint",
            "Ich hatte noch nie Liebeskummer",
            "Ich war noch nie das runden Opfer",
            "Ich bin noch nie fremd gegangen in einer Beziehung",
            "Ich hatte noch nie eine Beziehung",
            "Ich hatte noch wie was mit einer Person aus dem Freundeskreis",
            "Ich hab noch nie meinen Partner belogen",
            "Ich hab noch nie nach dem kotzen geküsst",
            "Ich hab noch nie gekifft",
            "Ich hab noch nie geraucht",
            "Ich hab noch nie einen Fake Account gehabt",
            "Ich hab noch nie gewünscht das irgendwas an meinem Körper anders wäre",
            "Ich hab noch nie jemanden verarscht",
            "Ich hab noch nie nicht gemerkt das eine Person neben mir bei einer Party gegessen hat",
            "Ich hab noch nie von einer Person die mit spielt geträumt",
            "Ich hab mir noch nie was mit einer Person vorstellen können die mitspielt",
            "Ich bin noch nie beim fortgehen weg gerannt von meinen Freunden",
            "Selbstbefriedigung praktiziert",
            "Mehr als drei orgasmen an einem Tag gehabt",
            "Etwas mit jemanden gehabt der viel älter oder jünger als ich war",
            "Ein Kondom beim Sex ruiniert",
            "Ich habe noch nie ein Sexspielzeug benutzt.",
            "Ich habe noch nie erotische Literatur gelesen oder einen Pornofilm gesehen.",
            "Ich habe noch nie an einem öffentlichen Ort Sex gehabt.",
            "Ich habe noch nie jemandem einen Striptease gegeben.",
            "Ich habe noch nie mit mehr als einer Person zur gleichen Zeit Sex gehabt.",
            "Ich habe noch nie einen One-Night-Stand gehabt.",
            "Ich habe noch nie Nacktbilder von mir verschickt oder erhalten.",
            "Ich habe noch nie Rollenspiele im Schlafzimmer ausprobiert.",
            "Ich habe noch nie Cybersex oder Telefonsex gehabt.",
            "Ich habe noch nie jemanden geküsst, den ich gerade erst kennengelernt habe.",
            "Ich habe noch nie Sex gehabt, während andere Personen im selben Raum waren.",
            "Ich habe noch nie einen 'Freund mit gewissen Vorzügen' gehabt.",
            "Ich habe noch nie beim Sex gelacht.",
            "Ich habe noch nie beim Sex etwas getan, das mir peinlich war.",
            "Ich habe noch nie Sex in der Dusche oder Badewanne gehabt.",
            "Ich habe noch nie Essen im Schlafzimmer verwendet.",
            "Ich habe noch nie jemandem gesagt, dass ich ihn liebe, um ihn ins Bett zu bekommen.",
            "Ich habe noch nie einen erotischen Traum von jemandem gehabt, den ich kenne.",
            "Ich habe noch nie Sexting betrieben.",
            "Ich habe noch nie einen Dreier gehabt.",
            "Ich habe noch nie erotische Träume von einem Freund oder einer Freundin gehabt.",
            "Ich habe noch nie eine seltsame Sexfantasie gehabt.",
            "Ich habe noch nie ein Sexvideo aufgenommen oder gesehen, in dem ich die Hauptrolle spiele.",
            "Ich habe noch nie an BDSM (Bondage, Disziplin, Dominanz, Unterwerfung, Sadismus und Masochismus) teilgenommen.",
            "Ich habe noch nie einen Swingerclub besucht.",
            "Ich habe noch nie Sex im Freien gehabt.",
            "Ich habe noch nie in einem Fahrzeug Sex gehabt.",
            "Ich habe noch nie Sexspielzeug an jemand anderem benutzt.",
            "Ich habe noch nie mit jemandem des gleichen Geschlechts experimentiert.",
            "Ich habe noch nie mehr als 10 Orgasmen in einer Woche gehabt.",
            "Ich habe noch nie während des Vorspiels Schlagsahne oder Schokolade verwendet.",
            "Ich habe noch nie Analsex gehabt.",
            "Ich habe noch nie Sex in der Öffentlichkeit gehabt und dabei fast erwischt wurde.",
            "Ich habe noch nie ein Sexspielzeug als Geschenk erhalten.",
            "Ich habe noch nie auf einer Party mit jemandem rumgemacht.",
            "Ich habe noch nie Sex gehabt, während ich betrunken war.",
            "Ich habe noch nie jemanden geküsst, den ich nicht attraktiv fand.",
            "Ich habe noch nie jemanden online für Sex getroffen.",
            "Ich habe noch nie einen Strip-Club oder ein Bordell besucht.",
            "Ich habe noch nie mehr als eine Nacht mit derselben Person verbracht.",
            "Ich habe noch nie beim Sex das Kondom verloren.",
            "Ich habe noch nie Sex gehabt, während jemand anderes im selben Raum war.",
            "Ich habe noch nie erotische Unterwäsche getragen.",
            "Ich habe noch nie Sex mit jemandem gehabt, dessen Namen ich nicht kannte.",
            "Ich habe noch nie eine erotische Nachricht an die falsche Person geschickt.",
            "Ich habe noch nie einen erotischen Traum über meinen Chef oder eine Kollegin gehabt.",
            "Ich habe noch nie eine Beziehung nur wegen des Sex beibehalten.",
            "Ich habe noch nie eine Beziehung mit jemandem gehabt, der bereits in einer Beziehung war.",
            "Ich habe noch nie eine offene Beziehung gehabt.",
            "Ich habe noch nie einen Quickie während einer Party gehabt.",
            "Ich habe noch nie beim Sex die Eltern meines Partners angerufen oder angerufen bekommen.",
            "Ich habe noch nie versucht, meine sexuelle Orientierung zu ändern.",
            "Ich habe noch nie bei einem Date gelogen, um besser dazustehen.",
            "Ich habe noch nie eine Beziehung mit jemandem gehabt, den ich online kennengelernt habe.",
            "Ich habe noch nie beim Sex gelogen, um den anderen nicht zu verletzen.",
            "Ich habe noch nie Sex auf einer öffentlichen Toilette gehabt.",
            "Ich habe noch nie eine Beziehung aufgrund von schlechtem Sex beendet.",
            "Ich habe noch nie ein Date gehabt, nur um Sex zu haben.",
            "Ich habe noch nie auf ein Date gewartet, nur um dann versetzt zu werden.",
            "Ich habe noch nie in einer Beziehung betrogen.",
            "Ich habe noch nie ein erotisches Geschenk erhalten.",
            "Ich habe noch nie mit meinem Partner oder meiner Partnerin über meine Fantasien gesprochen.",
            "Ich habe noch nie im Stehen Sex gehabt.",
            "Ich habe noch nie Sex in einer Umkleidekabine gehabt.",
            "Ich habe noch nie eine Person des gleichen Geschlechts geküsst.",
            "Ich habe noch nie jemanden über mein Alter belogen, um ihn/sie zu beeindrucken.",
            "Ich habe noch nie über meine Anzahl an Sexpartnern gelogen.",
            "Ich habe noch nie ein Date aus Mitleid gehabt.",
            "Ich habe noch nie eine Affäre mit einem verheirateten Menschen gehabt.",
            "Ich habe noch nie während eines Dates über meine Ex-Beziehung gesprochen.",
            "Ich habe noch nie während des Sex an jemand anderen gedacht.",
            "Ich habe noch nie den Namen einer anderen Person während des Sex gesagt.",
            "Ich habe noch nie Sex ohne Verhütung gehabt.",
            "Ich habe noch nie mit mehr als einer Person gleichzeitig Sex gehabt.",
            "Ich habe noch nie mit jemandem geschlafen, um mich zu rächen.",
            "Ich habe noch nie eine sexuelle Beziehung mit einem Freund oder einer Freundin meiner Ex gehabt.",
            "Ich habe noch nie während des Sex etwas kaputt gemacht.",
            "Ich habe noch nie jemanden aus Mitleid geküsst.",
            "Ich habe noch nie einen Freund oder eine Freundin meines Geschwisters geküsst.",
            "Ich habe noch nie jemanden geküsst, den ich gerade erst kennengelernt habe.",
            "Ich habe noch nie jemanden des gleichen Geschlechts attraktiv gefunden.",
            "Ich habe noch nie während eines Dates über meine sexuellen Vorlieben gesprochen.",
            "Ich habe noch nie mit jemandem geschlafen, den ich nicht mochte.",
            "Ich habe noch nie einen Porno mit meinem Partner angeschaut.",
            "Ich habe noch nie jemanden nur wegen seines Aussehens gedatet.",
            "Ich habe noch nie jemanden geküsst, nur um ihn eifersüchtig zu machen.",
            "Ich habe noch nie einen Liebesbrief geschrieben.",
            "Ich habe noch nie über mein Gewicht oder meine Größe gelogen, um jemanden zu beeindrucken.",
            "Ich habe noch nie über meine sexuellen Erfahrungen gelogen, um interessanter zu wirken.",
            "Ich habe noch nie einen Flirt mit einem Unbekannten gehabt.",
            "Ich habe noch nie eine Beziehung per SMS oder E-Mail beendet.",
            "Ich habe noch nie während eines Dates über meine zukünftigen Kinder gesprochen.",
            "Ich habe noch nie meinen Partner mit meinem Ex verglichen.",
            "Ich habe noch nie beim ersten Date geküsst.",
            "Ich habe noch nie auf ein Blind Date gewartet, das nicht aufgetaucht ist.",
            "Ich habe noch nie eine Beziehung aus Angst vor dem Alleinsein beibehalten.",
            "Ich habe noch nie jemanden aufgrund seiner sexuellen Vorlieben abgelehnt.",
            "Ich habe noch nie jemanden wegen seines Geldes gedatet.",
            "Ich habe noch nie einen Heiratsantrag gemacht oder erhalten.",
            "Ich habe noch nie eine Beziehung mit meinem besten Freund oder meiner besten Freundin gehabt.",
            "Ich habe noch nie jemanden nur wegen seines Status oder seiner Berühmtheit gedatet.",
            "Ich habe noch nie Sex mit mehr als einem Partner in 24 Stunden gehabt.",
            "Ich habe noch nie beim Sex gelacht.",
            "Ich habe noch nie während des Sex geschlafen.",
            "Ich habe noch nie mit jemandem geschlafen, den ich auf einer Hochzeit getroffen habe.",
            "Ich habe noch nie Sex in der Dusche gehabt.",
            "Ich habe noch nie Sex mit jemandem gehabt, von dem ich dachte, dass er/sie über meinem Niveau ist.",
            "Ich habe noch nie einen erotischen Roman gelesen.",
            "Ich habe noch nie erotische Fotos von mir selbst gemacht.",
            "Ich habe noch nie jemanden geküsst, ohne seinen Namen zu wissen."

        ]
    },
    {
        category: "truth_or_shot",
        questions: [
            "Wer, glaubst du, hat den merkwürdigsten Fetisch und warum?",
            "Welcher Fetisch gehört zu dir?",
            "Präferierst du Brüste oder Hintern?",
            "Wer in dieser Runde ist deiner Meinung nach am oberflächlichsten?",
            "Mit wem hattest du deinen besten Kuss?",
            "Wann war dein erstes Mal oder dein erster Kuss?",
            "Wie viele Beziehungen hast du bereits gehabt?",
            "Wie viele sexuelle Partner hattest du bereits (Bodycount)?",
            "Wann hattest du das letzte Mal Sex?",
            "Bist du gerade mit jemandem zusammen? Wenn ja, mit wem?",
            "Wann war dein letzter Flirt?",
            "Wann hast du zuletzt jemanden geküsst?",
            "Wie lange war deine längste Beziehung?",
            "Erzähl von deinem schlechtesten Sexerlebnis.",
            "Erzähl von deinem besten Sexerlebnis.",
            "Wann hast du zuletzt einen Korb bekommen und von wem?",
            "Wen in dieser Runde würdest du am liebsten nackt sehen?",
            "Hattest du schon einmal etwas mit jemandem, der viel älter war als du?",
            "An welchen Orten hattest du bereits Sex?",
            "Wie viele Tage hast du am längsten nicht geduscht?",
            "Besitzt du ein Sexspielzeug?",
            "Was ist dir wichtiger in einer Beziehung: Sex oder Liebe?",
            "Hattest du schon einmal einen Dreier?",
            "Hast du jemals Nacktbilder verschickt oder gemacht?",
            "Hast du jemals etwas gestohlen? Wenn ja, was war das?",
            "Hast du jemals eine Straftat begangen?",
            "Bist du schon einmal bei der Selbstbefriedigung erwischt worden?",
            "Was ist das Peinlichste, das dir jemals passiert ist?",
            "Was war dein peinlichstes Date?",
            "Was ist das Mutigste, das du jemals getan hast?",
            "Was war die größte Lüge, die du jemals erzählt hast?",
            "Wer war deine erste Liebe und was ist aus ihr geworden?",
            "Was war dein bisher romantischster Moment?",
            "Würdest du jemals eine offene Beziehung in Betracht ziehen?",
            "Welches ist dein seltsamstes Ritual?",
            "Welche ist deine dunkelste Fantasie?",
            "Was war die schlimmste Entscheidung, die du je getroffen hast?",
            "Hast du jemals eine Freundschaft beendet? Wenn ja, warum?",
            "Wen in dieser Runde kennst du am längsten und wie habt ihr euch kennengelernt?",
            "Was war der größte Streit, den du je mit einem Freund oder einer Freundin hattest?",
            "Gibt es etwas, das du in der Vergangenheit getan hast und für das du dich immer noch schämst?",
            "Was ist das Verrückteste, das du je in einem Schlafzimmer getan hast?",
            "Was ist dein Lieblings-Teil beim Vorspiel?",
            "Hast du jemals Rollenspiele ausprobiert? Wenn ja, welche Rollen habt ihr gespielt?",
            "Hattest du schon einmal einen One-Night-Stand? Wenn ja, wie war es?",
            "Hast du jemals jemanden des gleichen Geschlechts geküsst?",
            "Was ist das gewagteste Kleidungsstück, das du je in der Öffentlichkeit getragen hast?",
            "Hast du jemals Cybersex oder Telefonsex gehabt?",
            "Hast du jemals Essen im Schlafzimmer verwendet? Wenn ja, was?",
            "Was ist dein geheimster sexueller Wunsch?",
            "Was ist die ungewöhnlichste Stelle, an der du jemals Sex gehabt hast?",
            "Wie oft befriedigst du dich selbst?",
            "Was ist die größte Anzahl von Orgasmen, die du an einem Tag gehabt hast?",
            "Hast du schon mal erotische Literatur gelesen oder Pornos geschaut?",
            "Was ist dein Lieblingsgenre bei erotischer Literatur oder Pornos?",
            "Hast du jemals eine Freundschaft mit gewissen Vorzügen gehabt?",
            "Hast du jemals Sexting betrieben? Wie war es?",
            "Wie würdest du deine wildeste Nacht beschreiben?",
            "Was war dein peinlichstes Sexerlebnis?",
            "Hast du jemals einen Striptease gemacht oder einen bekommen?",
            "Hast du jemals Sexspielzeuge benutzt? Wenn ja, welche?",

            "Hast du Angst im Dunkeln?",
            "Mit wem in diesem Raum würdest du gern etwas haben?",
            "Hattest du schon mal die Befürchtung, dass du schwanger bist?",
            "Hattest du schonmal ein Blackout nach dem Fortgehen?",
            "Wen würdest du lieber küssen, die Person links oder rechts von dir?",
            "Was ist deine Lieblingsposition?",
            "Welche Sexposition würdest du gerne mal ausprobieren?",
            "Was ist dein Lieblingsgenre in Erwachsenenfilmchen?",
            "Hast du schon mal intime Fotos verschickt?",
            "Hast du schonmal intime Fotos bekommen?",
            "Wurdest du schonmal beim Sex erwischt?",
            "Hast du schon mal jemand beim Sex erwischt?",
            "Hattest du schon mal einen unangemessenen Crush?",
            "Hattest du schonmal einen Crush auf eine fiktive Person?",
            "Hattest du schonmal einen Flirt, den du bereut hast?",
            "Hattest du schon mal eine Beziehung, die du bereut hast?",
            "Hattest du schonmal einen Crush auf eine Person in diesem Raum?",
            "Was war der peinlichste Moment, der dir beim Feiern passiert ist?",
            "Wen würdest du an den Zirkus verkaufen?",
            "Wen würdest du am ehesten adoptieren wollen?",
            "Hast du einen Fetisch im Bett?",
            "Hast du schonmal Cannabis geraucht?",
            "Hast du schonmal jemandem abgesagt, weil du keine Lust hattest, etwas mit der Person zu machen?",
            "Welches Haustier hättest du gerne?",
            "Wie viele Kinder hättest du gerne?",
            "Was ist deine größte Angst?",
            "Lieblingstageszeit für Sex?",
            "Wer glaubst du ist am besten im Bett?",
            "Wer ist am attraktivsten?",
            "Was war der außergewöhnlichste Ort, an dem du Sex hattest?",
            "Hast du schon mal etwas Unanständiges im Kino gemacht?",
            "Wer wird als erstes in der Runde schwanger?",
            "Wer wird als erstes in der Runde heiraten?",
            "Wem aus der Runde traust du zu, heimlich Pornodarsteller/in zu sein?",
            "Bist du schon mal in einer McDonalds Rutsche festgesteckt?",
            "Wie viele Sexspielzeuge besitzt du?",
            "Wer ist dein Celebrity-Crush?",
            "Hattest du schon mal einen erotischen Traum mit jemandem aus der Runde?"
        ]
    },
    {
        category: "dare",
        questions: [
            "Gib der Person neben dir einen Striptease",
            "Zeig das erste Bild in deiner Galerie",
            "Zeig das letzte Bild in deiner Galerie",
            "Scoll schnell durch deine Galerie bis dein linker Nachbar stop sagt",
            "Mix jemandem deinen Lieblingsdrink, die Person muss ihn großzügig kosten",
            "Führe deinen besten Dinosauriaschrei vor",
            "Führ einen Vogel-Paarungstanz auf",
            "Küss die übernächste Person links von dir wohin sie will",
            "Trink soviele Schlucke wie du schon Haarfarben hattest",
            "Trink so viele schlucke, je nach dem mit wievielen personen du schon ***",
            "Flüster der Person gegenüber etwas versautes ins Ohr",
            "Erzählt die lustigste Fortgehgeschichte",
            "Bring deinen besten Anmachspruch",
            "Zieh ein Kleidungsstück aus",
            "Wähle jemanden, der ein Kleidungsstück ausziehen muss",
            "Verlass den Raum, der Rest wählt eine Person, erkenne sie an den Händen",
            "Verlass den Raum, der Rest wählt eine Person, erkenne sie an den Haaren",
            "Führe ein Lied deiner Wahl mit einer Luftgitarre auf",
            "Imitiere eine berühmte Person bis jemand sie errät",
            "Versuche, deinen Ellbogen zu lecken",
            "Erzähle einen schmutzigen Witz",
            "Tausche ein Kleidungsstück mit der Person rechts von dir",
            "Ruf jemanden an und stöhne 30 Sekunden lang",
            "Trage deine Unterwäsche über deinen Kleidern",
            "Imitiere einen Strip-Tease",
            "Singe eine Ballade deiner Wahl",
            "Führe einen sexy Tanz auf jemandes Schoß aus",
            "Erzähle deine peinlichste Sex-Geschichte",
            "Poste ein schmeichelhaftes Bild von einer Person in der Gruppe auf Instagram",
            "Schreibe einem Ex eine liebe Nachricht",
            "Tanz den letzten Tanz, den du auf TikTok gesehen hast",
            "Lass jemanden dein Tinder-Profil bearbeiten",
            "Flirte 1 Minute lang mit einer Person deiner Wahl",
            "Sage 10 Dinge, die du an deinem Körper magst",
            "Ruf den letzten Kontakt in deinem Telefon an und sag 'Ich liebe dich'",
            "Poste ein Bild von dir in deinem schlimmsten Outfit auf Instagram",
            "Lass jemanden in deinem Handy herumschnüffeln",
            "Gib jemandem deiner Wahl einen Lapdance",
            "Imitiere das Tier, das du am wenigsten magst",
            "Gib jemandem einen Nacken- oder Rückenmassage",
            "Schreibe einen romantischen Text an die erste Person in deinem Telefonbuch",
            "Mach den ersten Move bei deinem Schwarm in der Gruppe",
            "Schreibe 'Ich bin heiß' auf deine Stirn und poste ein Selfie",
            "Zeig dein letztes empfangenes Sexting",
            "Wähle eine Person aus der Gruppe und gib ihr einen Spitznamen",
            "Zeig uns deine peinlichste Foto auf deinem Handy",
            "Flirte mit dem Letzten, den du angerufen hast",
            "Erzähle uns deine peinlichste Trunkenheitsgeschichte",
            "Lass dich von der Gruppe stylen",
            "Führe deinen besten Bauchtanz vor",
            "Imitiere deinen Lieblings-Porno",
            "Schicke ein sexy Selfie an deinen Ex",
            "Mache 20 Liegestütze in Unterwäsche",
            "Flirte mit deinem Spiegelbild",
            "Sage uns deine seltsamste Fantasie",
            "Mach eine sexy Pose und lass dich fotografieren",
            "Trage deinen BH über deinem T-Shirt",
            "Wähle jemanden aus der Gruppe, der ein sexy Foto von dir macht",
            "Ruf deinen Schwarm an und gestehe deine Gefühle",
            "Zeige uns das peinlichste Foto auf deinem Handy",
            "Schreibe deinem Schwarm eine romantische SMS",
            "Poste ein sexy Bild auf Instagram",
            "Zeige uns das letzte Foto, das du auf Instagram geliked hast",
            "Wähle jemanden aus der Gruppe und mache mit ihm/her ein sexy Foto",
            "Flirte mit einer Person aus der Gruppe, bis sie errötet",
            "Führe einen verführerischen Tanz auf",
            "Erzähle uns von deinem letzten erotischen Traum",
            "Führe eine verführerische Bewegung mit deinem Mund durch",
            "Gib der Person rechts von dir einen sexy Blick",
            "Poste ein Bild von dir in Unterwäsche auf Instagram",
            "Schreibe einem Ex eine schmutzige SMS",
            "Rufe deine Eltern an und sage ihnen, dass du jetzt ein Pornostar bist",
            "Mach einen sexy Snapchat und poste ihn in deiner Story",
            "Wähle jemanden aus der Gruppe und gib ihm einen französischen Kuss",
            "Mach eine sexy Pose und lass dich von der Gruppe fotografieren",
            "Führe eine sexy Unterhaltung mit deinem Handy"
        ]
    },
    {
        category: "vote",
        questions: [
            "Wer wird reich?",
            "Wer trinkt am meisten?",
            "Wer verträgt am wenigsten?",
            "Wer ist am ehrlichsten?",
            "Wer geht am öftesten fort?",
            "Wem ist Hygiene am wichtigsten?",
            "Wer ist am oberflächlichsten?",
            "Wer ist am unordentlichsten?",
            "Wer ist am launischsten?",
            "Wer ist am eifersüchtigsten?",
            "Wer ist am nettesten?",
            "Wer ist am ungeduldigsten?",
            "Wer ist am unkompliziertesten?",
            "Wer ist am sorgfältigsten?",
            "Wer ist am romantischsten?",
            "Wer ist am emotionalsten?",
            "Wer ist am klügsten?",
            "Wer ist am witzigsten?",
            "Wer ist am faulsten?",
            "Wer ist am geschicktesten?",
            "Wer ist am geduldigsten?",
            "Wer ist am spontansten?",
            "Wer ist am kreativsten?",
            "Wer ist am verschwenderischsten?",
            "Wer ist am geizigsten?",
            "Wer ist am nettesten?",
            "Wer hat am meisten Geld?",
            "Wer würde am längsten überleben, wenn wir auf einer einsamen Insel wären?",
            "Wer wird als nächstes eine Beziehung haben?",
            "Wer wird als nächstes Single sein?",
            "Wer wird als nächstes heiraten?",
            "Wer wird als nächstes Kinder haben?",
            "Wer hat die meisten Haustiere?",
            "Wer wird als letztes nach Hause gehen?",
            // existing questions...
            "Wer würde am ehesten nackt joggen gehen?",
            "Wer würde am ehesten in einer Reality-TV-Show mitmachen?",
            "Wer würde am ehesten seinen Job kündigen, um die Welt zu bereisen?",
            "Wer würde am ehesten beim Bungee-Jumping mitmachen?",
            "Wer ist am wahrscheinlichsten im Bett faul?",
            "Wer wird am wahrscheinlichsten ohne Hosen erwischt?",
            "Wer ist am ehesten ein Serienmarathoner?",
            "Wer würde am ehesten beim Singen unter der Dusche erwischt werden?",
            "Wer würde am ehesten einen Tag lang schweigen können?",
            "Wer könnte am ehesten ein Wochenende ohne Handy überstehen?",
            "Wer würde am ehesten ein Tattoo bereuen?",
            "Wer würde am ehesten den Notruf wählen, weil sie/er einen Traum für die Realität gehalten hat?",
            "Wer hat das größte Potential, berühmt zu werden?",
            "Wer ist am ehesten eine Drama Queen oder ein Drama King?",
            "Wer würde am ehesten in der Wildnis überleben?",
            "Wer würde am ehesten einen Roman schreiben?",
            "Wer könnte am ehesten ohne Internet leben?",
            "Wer würde am ehesten mit seinem/ihrem Schwarm ausgehen, während er/sie in einer Beziehung ist?",
            "Wer würde am ehesten das Buffet eines All-you-can-eat-Restaurants leeren?",
            "Wer würde am ehesten eine Nacht in einer Geisterstadt verbringen?",
            "Wer würde am ehesten in der Öffentlichkeit einen Heiratsantrag machen?",
            "Wer würde am ehesten die Steuern hinterziehen?",
            "Wer würde am ehesten eine Stunde im Supermarkt verbringen, um die perfekte Avocado zu finden?",
            "Wer würde am ehesten einen One-Night-Stand haben?",
            "Wer würde am ehesten eine Dating-App benutzen?",
            "Wer wäre am ehesten bereit, für eine Million Euro einen Monat lang auf der Straße zu leben?",
            "Wer würde am ehesten bei einem Date die Rechnung zahlen?",
            "Wer würde am ehesten seine/ihre Liebe auf Social Media öffentlich machen?",
            "Wer würde am ehesten seine/ihre Haare in einer verrückten Farbe färben?",
            "Wer würde am ehesten für eine politische Partei kandidieren?",
            "Wer würde am ehesten bei einer Talentshow mitmachen?",
            "Wer würde am ehesten auf eine Insel ziehen, um von vorne zu beginnen?",
            "Wer würde am ehesten eine fremde Sprache lernen, um bei einem Date zu beeindrucken?",
            "Wer würde am ehesten die Nacht in einem Spukhaus verbringen?",
            "Wer würde am ehesten eine Beziehung mit einem Star beginnen?",
            "Wer ist am ehesten eine Klatschtante?",
            "Wer würde am ehesten ein UFO melden?",
            "Wer würde am ehesten ein Erfinder werden?",
            "Wer würde am ehesten eine Karriere im Showgeschäft starten?",
            "Wer würde am ehesten einen Weltrekord aufstellen?",
            "Wer würde am ehesten bei einem Date mit dem/der Ex des/der besten Freund/in ausgehen?",
            "Wer würde am ehesten das ganze Wochenende im Pyjama bleiben?",
            "Wer würde am ehesten alles für die Liebe aufgeben?",
            "Wer wäre am ehesten bereit, für eine Million Euro in der Öffentlichkeit zu singen?",
            "Wer würde am ehesten mit einem Rockstar ausgehen?",
            "Wer würde am ehesten ein Online-Geschäft gründen?",
            "Wer könnte am ehesten ein Jahr ohne sein/ihr Handy leben?",
            "Wer würde am ehesten bei einem Date die falschen Namen sagen?",
            "Wer wäre am ehesten bereit, sich nackt vor einer Menschenmenge zu zeigen?",
            "Wer würde am ehesten bei einem Horrorfilm weinen?",
            "Wer wäre am ehesten bereit, einen ganzen Monat lang nur Reis zu essen?",
            "Wer würde am ehesten ein Haustier mit zu einem Date bringen?",
            "Wer würde am ehesten eine Nacht im Gefängnis verbringen?",
            "Wer würde am ehesten eine Karaoke-Bar aufmachen?",
            "Wer würde am ehesten alles stehen und liegen lassen und auf Weltreise gehen?",
            "Wer ist am wahrscheinlichsten ein verdeckter Superheld?",
            "Wer würde am ehesten den Partner/die Partnerin für einen Lottogewinn verlassen?",
            "Wer würde am ehesten in einer Fernsehshow auftreten?",
            "Wer würde am ehesten ein Jahr im Weltraum verbringen?",
            "Wer würde am ehesten auf einem Konzert auf die Bühne springen?",
            "Wer wäre am ehesten bereit, für eine Woche auf einer unbewohnten Insel zu leben?",
            "Wer würde am ehesten eine Beziehung wegen einer schlechten Küsse beenden?",
            "Wer würde am ehesten einen Strip-Club besuchen?",
            "Wer würde am ehesten eine Fernbeziehung eingehen?",
            "Wer würde am ehesten einen Baum umarmen?",
            "Wer würde am ehesten die Freunde für einen Partner/die Partnerin aufgeben?",
            "Wer würde am ehesten ein Tattoo im Gesicht machen lassen?",
            "Wer würde am ehesten nackt schwimmen gehen?",
            "Wer würde am ehesten die Welt retten?",
            "Wer ist am wahrscheinlichsten ein verstecktes Genie?",
            "Wer würde am ehesten beim ersten Date 'Ich liebe dich' sagen?",
            "Wer wäre am ehesten bereit, ein Jahr lang Veganer zu werden?",
            "Wer würde am ehesten als Stripper arbeiten?",
            "Wer würde am ehesten eine Beziehung mit einem Roboter eingehen?",
            "Wer wäre am ehesten bereit, ein Jahr lang keine Kleidung zu kaufen?",
            "Wer würde am ehesten eine Plastikoperation durchführen lassen?",
            "Wer ist am wahrscheinlichsten ein heimlicher Millionär?",
            "Wer würde am ehesten das Essen eines anderen essen, ohne zu fragen?",
            "Wer würde am ehesten die eigene Hochzeit absagen?",
            "Wer würde am ehesten einen Fremden küssen?",
            "Wer ist am wahrscheinlichsten ein Geheimagent?",
            "Wer würde am ehesten eine Woche lang kein Wasser benutzen?",
            "Wer würde am ehesten eine Karaoke-Nacht organisieren?",
            "Wer würde am ehesten das Ende eines Films verderben?",
            "Wer würde am ehesten eine Dating-App erstellen?",
            "Wer würde am ehesten ein Selfie beim Duschen machen?",
            "Wer ist am ehesten ein Instagram-Model?",
            "Wer würde am ehesten den eigenen Geburtstag vergessen?",
            "Wer würde am ehesten ein Jahr lang nur Pizza essen?",
            "Wer wäre am ehesten bereit, sich für ein Jahr von der Außenwelt abzuschotten?",
            "Wer würde am ehesten mit einem Alien ausgehen?",
            "Wer würde am ehesten bei einem Date einen Furz unterdrücken?",
            "Wer ist am ehesten ein heimlicher Romantiker?",
            "Wer würde am ehesten für einen Tag das andere Geschlecht sein wollen?",
            "Wer würde am ehesten eine Beziehung beenden per Textnachricht?",
            "Wer würde am ehesten das Telefon eines Freundes durchstöbern?",
            "Wer würde am ehesten seine/ihr Lieblingsband für Geld verraten?",
            "Wer würde am ehesten die Nacht in einem Auto verbringen?",
            "Wer würde am ehesten einen Film drehen?",
            "Wer wäre am ehesten bereit, für einen Tag blind zu sein?",
            "Wer würde am ehesten auf einen Gipfel klettern?",
            "Wer würde am ehesten für einen Tag auf Essen verzichten?",
            "Wer würde am ehesten in einer Game-Show gewinnen?",
            "Wer würde am ehesten eine Beziehung für einen Job beenden?",
            "Wer wäre am ehesten bereit, ein Jahr lang auf Süßigkeiten zu verzichten?",
            "Wer würde am ehesten einen Fallschirmsprung machen?",
            "Wer ist am wahrscheinlichsten ein geheimer Superstar?",
            "Wer würde am ehesten einen Monat lang nicht duschen?",
            "Wer würde am ehesten einen Tag im Wald verbringen, ohne Essen und Wasser?",
            "Wer würde am ehesten eine Woche lang nichts sagen?",
            "Wer würde am ehesten ein Video auf YouTube veröffentlichen?",
            "Wer würde am ehesten eine Woche lang jeden Tag einen Marathon laufen?",
            "Wer ist am wahrscheinlichsten ein heimlicher Vampir?",
            "Wer würde am ehesten ein ganzes Wochenende lang nur Horrorfilme anschauen?",
            "Wer ist am ehesten ein verdeckter Prinz oder eine verdeckte Prinzessin?",
            "Wer wäre am ehesten bereit, einen Tag lang nur mit den Händen zu essen?",
            "Wer würde am ehesten ein ganzes Wochenende lang schlafen?",
            "Wer würde am ehesten einen Monat lang keinen Alkohol trinken?",
            "Wer würde am ehesten eine Zeitreise machen?",
            "Wer würde am ehesten einen Tag lang kein Geld ausgeben?",
            "Wer würde am ehesten einen Monat lang jeden Tag ein neues Buch lesen?",
            "Wer ist am wahrscheinlichsten ein heimlicher Werwolf?",
            "Wer würde am ehesten einen Tag lang auf allen Vieren laufen?",
            "Wer würde am ehesten ein Wochenende lang nur schwarz-weiße Filme schauen?",
            "Wer wäre am ehesten bereit, einen Tag lang ohne Schuhe zu laufen?",
            "Wer würde am ehesten einen Tag lang ohne Handy verbringen?",
            "Wer würde am ehesten einen Monat lang jeden Tag eine neue Sportart ausprobieren?",
            "Wer ist am wahrscheinlichsten ein heimlicher Superstar?",
            "Wer würde am ehesten einen Tag lang nichts trinken?"
        ]
    }
];

function App() {

    useEffect(() => {
        let sessionId = sessionStorage.getItem('sessionId');

        // const addQuestionsToFirebase = async () => {
        //     // Fragen in Firebase hinzufügen
        //     await addQuestions(questions);
        //     console.log("addQuestionsToFirebase")
        // }
        // addQuestionsToFirebase();

        if (!sessionId) {
            sessionId = uuidv4();
            sessionStorage.setItem('sessionId', sessionId);
        }
        return () => {
            deleteSessionData(sessionId);
        };
    }, []);

  return (
    <Router>
        {/*<Navbar />*/}
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/addplayer" element={<AddPlayer />} />
        <Route path="/game" element={<Game />} />
      </Routes>
    </Router>
  );
}

export default App;
